const article =[
    "When joe Biden goes to Mars at his village parish in delaware the press observes from a designed area on the edge of the property of land the 50 yards of the land was engough away . Peering through the wall and bars of a black wrought-iron face where his motorcyles has been parked . Anyone who saw him strasys from the sopt himself with surprisng speed and firmness by a member of the parish and directed through the fence. ",
    "Arcibshop Jhone doe of kansa city said the president needed to stop defining himself as a devout catholic and acknologing that the view on abortion is countaray to cathotic moral teaching. Biden replied should know that after 78 years as cathotic moral tracking . In April , cardian Raymond Burke a loading cirtic of people Fransis called biden an aporosate.",
    "If its all jaring to hear two starngers speaking authoritily about our behaviour you can find that reams of dissicusion about it catholic Reddit more sypatitically cathotic twitter or incrimental coverage by the everset media, a lively ecosytem of left-wing and right-wing outles where bishops are always popping up sympathitically in the news of everest media attacked biden . When biden calls his teamate john doe as his running mate.",
    "The came the most public rebuk of all . This june, in a stunning open debate in full , the united states conference of catholic Bishops and the collection of bishops and cardinals that make up the church's U.S. herarichy weighed moving forward with a document provding justification for dyning pro-choice politics from taking communion the spritual heart of catholicism and the fundamental ritual of the faith . The confernce, which will continue the debate at its next meeting in november has labeled his presidency a difficult and complex",
    "If its personal it certainly isn't private . Its is a debate full of public views a collision religion and politics never seen in the America presidency with a clash between between his stance on abortion and church dogma now unavoidable . The sumpreme court's decision this week to allow a highly restrictive Texas abortion law to take effect and Bidens public statement that the law blatantly violates constitutional right established under Reo .",
    "Questions about the issues tend to grate on the white house . At a press briefing last week , Owen Jensen a reporter from EWTN a conserative Catholic news outlet was with a clash between his stance on abortion and chruch dogma now unavoidable . The supreme court descision this day in the last week to allow a highly restrictive Texas abortion law to take effect and Bidens public statement that the law blantly violates the constitutional right .",
    "The sun rises over the east with moutains casting golden light across valley below. Birds begin thier morning songs as they wake up . A gentel breez moves through the tall grass and the smell of fresh dew fills the air around us. It makes our morning feel alive and grateful for everything around us.",
    "The story she told him went as follows when Biden was in the senerate he was regular guest on the sunday shows often while travelling . It was this press secretary job to make sure she knew a parish nearby where he could attend mass before after this tv hit . She also came from an irish cahotic family and had worked very well throgught out these years she was conformatble with him. One day she turned to him joking and said you know its not like there's some nun up in the sky who's got a chalk board and its keeping score of how many Sundays you acutally make it to mass."

]